name: Tryone
on:
  push
    tags:
      - "*"

jobs:
  job1:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Cat README
        run: |
          sed -i "s/_GIT_VERSION_/$(git describe --tags)/" README.md
          cat README.md