name: Tryone
on:
  push:


jobs:
  job1:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Cat README
        run: |
          V=$(git describe --tags | tr -d 'v' | tr '-' '.' | cut -d'.' -f 1-4)
          sed -i "s/_GIT_VERSION_/$V/" README.md
          cat README.md