name: Tryone
on:
  push

jobs:
  job1:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Cat README
        run: |
          ls
          git describe --tags
          cat README.md
